name: volatility-garch-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - requests
  - pip
  - pip:
      - arch
